# Proyecto de Análisis de Datos: Actividades Asociadas a Ataques de Tiburón

# 0 Enfoque

Objetivo del estudio 
El propósito de este proyecto es identificar qué actividades acuáticas aparecen con mayor frecuencia asociadas a ataques de tiburón   
segun los datos analizados de la web "(Global Shark Attack File)".

 Se basa en datos que no estan en tiempo real

A través de un proceso completo de:

exploración inicial

selección de variables relevantes

limpieza y normalización

análisis exploratorio (EDA)

visualización

análisis complementario de fatalidad

buscamos comprender en qué contextos y actividades se registran más incidentes.

# 1 Carga del dataset

In [4]:
import pandas as pd 
df = pd.read_excel("GSAF5.xls", engine="xlrd")
df.head() # Se visualizan las primeras filas para comprender la estructura general del dataset.

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2 Exploración inicial

Primero vemos alguna informacion del dataframe y como estan los ejes

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7087 entries, 0 to 7086
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7087 non-null   object
 1   Year            7085 non-null   float64
 2   Type            7069 non-null   str
 3   Country         7037 non-null   str
 4   State           6600 non-null   str
 5   Location        6520 non-null   str
 6   Activity        6504 non-null   str
 7   Name            6869 non-null   str
 8   Sex             6509 non-null   str
 9   Age             4093 non-null   object
 10  Injury          7051 non-null   str
 11  Fatal Y/N       6526 non-null   object
 12  Time            3560 non-null   object
 13  Species         3956 non-null   str
 14  Source          7067 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   str
 17  href            6796 non-null   str
 18  Case Number     6798 non-null   str
 19  Case Number.1   6797 non-null   str
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      str
 22  Unnamed: 22     2 non-null      str
dtypes: float64(2), object(6), str(15)
memory usage: 1.2+ MB

  
El dataset tiene 23 columnas, aunque visualmente parezcan menos.

Los nombres están desordenados, con espacios y formatos inconsistentes.

In [6]:
df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

# 3 Limpieza de nombres de columnas (Capital Case)

Para escoger las columnas que hacemos el estudio primero vamos a limpiar ese indice y dejarlas en Capital Case

In [7]:
df.columns = (
    df.columns
      .astype(str)
      .str.strip()
      .str.title()
      .str.replace(" ", "")
)

In [8]:
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,Pdf,HrefFormula,Href,CaseNumber,CaseNumber.1,OriginalOrder,Unnamed:21,Unnamed:22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns # Comprobamos visualmente

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'FatalY/N', 'Time', 'Species', 'Source',
       'Pdf', 'HrefFormula', 'Href', 'CaseNumber', 'CaseNumber.1',
       'OriginalOrder', 'Unnamed:21', 'Unnamed:22'],
      dtype='str')

# 4 Selección de columnas relevantes

 Columna   : Descripción         
 Date      : Para ver la estacion     
 Year      : Año del ataque      
 Type      : Provocado / No provocado   
 Country   : País del incidente      
 Activity  : Actividad registrada     
 Sex       : Sexo de la víctima      
 Age       : Edad (convertida a numérico) 
 Species   : Specie de tiburion      
 Fatal Y/N : Si fue fatal

Ahora escogemos la lsita que queramos usar sin miedo MANUAL

In [10]:
lista_escogida = [
    "Date",
    "Year",
    "Type",
    "Country",
    "Activity",
    "Sex",
    "Age",
    "Species",
    "FatalY/N"   # OJITO CON ESTE me dio muchos problemas
]

Para asegurarno que estan todas en la lista primero haremos un

In [11]:
def comprueba_estan(lista, df):
    for x in lista:
        if x in df.columns:
            print(f"{x} → OK")
        else:
            print(f"{x} → NO está en el DataFrame")

Comprueba si la lista esta:

In [12]:
comprueba_estan(lista_escogida,df)

Date → OK
Year → OK
Type → OK
Country → OK
Activity → OK
Sex → OK
Age → OK
Species → OK
FatalY/N → OK

# 6 Selección final del DataFrame

Ahora aplico el filtro al DataFrame

In [13]:
df = df[lista_escogida]
df.head()

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,UNprovoked,Maldives,Swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,Diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,Surfing,M,30+,Unknown,N

# Limpieza Datos de esas columnas

Limpiar espacios y normalizar texto en columnas clave
.astype(str).str.strip().str.lower()
.astype(str).str.strip().str.title()
.astype(str).str.strip().str.title()
.astype(str).str.strip().str.upper()

In [ ]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,UNprovoked,Maldives,Swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,Diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,Surfing,M,30+,Unknown,N

Activity → minúsculas para análisis (surf, swimming, fishing…)

In [15]:
df["Activity"] = df["Activity"].astype(str).str.strip().str.lower()

In [16]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,UNprovoked,Maldives,swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,USA,surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,?,Unknown shark 5ft (1.5m),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,?,Great White Shark 10ft (3m),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55,Tiger or bull shark implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,?,Juvenile Tiger shark 7ft (2.1m),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13,Unknown bull and tiger sharks frequent the area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,?,1.7m Seven Gill shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39,Bull shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11,Bull shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27,5m shark species not determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12,Bull shark,Y
18,13th January,2026.0,Unprovoked,USA,surfing,M,26,Suspected GWS,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N

Country → Capital Case (Australia, South Africa…)

In [17]:
df["Country"]  = df["Country"].astype(str).str.strip().str.title()

In [18]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,UNprovoked,Maldives,swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,?,Unknown shark 5ft (1.5m),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,?,Great White Shark 10ft (3m),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55,Tiger or bull shark implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,?,Juvenile Tiger shark 7ft (2.1m),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13,Unknown bull and tiger sharks frequent the area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,?,1.7m Seven Gill shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39,Bull shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11,Bull shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27,5m shark species not determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12,Bull shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26,Suspected GWS,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N

Type → Provoked / Unprovoked y no UNprovoked

In [19]:
df["Type"]     = df["Type"].astype(str).str.strip().str.title()

In [20]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,?,Unknown shark 5ft (1.5m),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,?,Great White Shark 10ft (3m),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55,Tiger or bull shark implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,?,Juvenile Tiger shark 7ft (2.1m),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13,Unknown bull and tiger sharks frequent the area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,?,1.7m Seven Gill shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39,Bull shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11,Bull shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27,5m shark species not determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12,Bull shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26,Suspected GWS,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N

Sex → M / F

In [21]:
df["Sex"]      = df["Sex"].astype(str).str.strip().str.upper()

In [22]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,?,Unknown shark 5ft (1.5m),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,?,Great White Shark 10ft (3m),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55,Tiger or bull shark implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,?,Juvenile Tiger shark 7ft (2.1m),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13,Unknown bull and tiger sharks frequent the area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,?,1.7m Seven Gill shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39,Bull shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11,Bull shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27,5m shark species not determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12,Bull shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26,Suspected GWS,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N

Species → Tiger Shark, White Shark…

In [23]:
df["Species"]  = df["Species"].astype(str).str.strip().str.title()

In [24]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,?,Great White Shark 3.5M (11.5Ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,?,Unknown Shark 5Ft (1.5M),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,?,Great White Shark 10Ft (3M),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55,Tiger Or Bull Shark Implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,?,Juvenile Tiger Shark 7Ft (2.1M),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,?,1.7M Seven Gill Shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26,Suspected Gws,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N

FatalY/N → Y / N

In [25]:
df["FatalY/N"] = df["FatalY/N"].astype(str).str.strip().str.upper()

In [26]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,?,Great White Shark 3.5M (11.5Ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,?,Unknown Shark 5Ft (1.5M),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,?,Great White Shark 10Ft (3M),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55,Tiger Or Bull Shark Implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,?,Juvenile Tiger Shark 7Ft (2.1M),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,?,1.7M Seven Gill Shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26,Suspected Gws,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,?,Unknown,N

Convertir la edad a número

In [28]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce") # COERCE convierte error a NaN

In [29]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,swimming,M,NaN,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16.0,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22.0,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,diving,M,NaN,Great White Shark 3.5M (11.5Ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,surfing,M,NaN,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39.0,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,swimming,F,NaN,Unknown Shark 5Ft (1.5M),N
7,10th March,2026.0,Unprovoked,Australia,wing foiling,M,NaN,Great White Shark 10Ft (3M),N
8,5th March,2026.0,Unprovoked,Australia,snorkeling,M,NaN,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55.0,Tiger Or Bull Shark Implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,diving,M,NaN,Juvenile Tiger Shark 7Ft (2.1M),N
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13.0,Unknown Bull And Tiger Sharks Frequent The Area,Y
12,29th January,2026.0,Unprovoked,Australia,surfing,M,NaN,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,swimming,F,NaN,1.7M Seven Gill Shark,N
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39.0,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11.0,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27.0,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12.0,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26.0,Suspected Gws,N
19,10th January,2026.0,Unprovoked,Australia,surfing,M,NaN,Unknown,N

Quitar valores Nan a todas columnas

In [30]:
for x in lista_escogida:
    df = df.dropna(subset=[x])

In [31]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16.0,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22.0,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39.0,Great White Shark,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55.0,Tiger Or Bull Shark Implicated,Y
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13.0,Unknown Bull And Tiger Sharks Frequent The Area,Y
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39.0,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11.0,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27.0,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12.0,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26.0,Suspected Gws,N
20,8th January,2026.0,Unprovoked,Us Virgin Islands,snorkeling,F,56.0,Unknown,Y
25,21st December,2025.0,Unprovoked,Usa,swimming,F,55.0,Great White Shark,Y
27,9th December,2025.0,Provoked,Usa,freeing trapped shark,M,24.0,Black Tip Reef Shark,N
28,27th November,2025.0,Unprovoked,Australia,swimming,M,26.0,3M Bull Shark,N
29,27th November,2025.0,Unprovoked,Australia,swimming,F,25.0,3M Bull Shark,Y
30,10th November,2025.0,Unprovoked,Australia,foil boarding,M,61.0,Great White Shark,N
31,9th November,2025.0,Unprovoked,French Polynesia,swimming,M,40.0,3M Shark,N
34,4th November,2025.0,Unprovoked,Samoa,surfing,M,13.0,Suspected Tiger Shark,N
35,14th October,2025.0,Unprovoked,Columbia,swimming with sharks,M,14.0,Nurse Shark,N
36,11th October,2025.0,Unprovoked,Australia,fishing/swimming,M,14.0,Tiger Or Bull Shark,N

Quitar TODAS las filas que tengan cualquier Nan

In [ ]:
df = df.dropna()

In [33]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16.0,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22.0,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39.0,Great White Shark,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55.0,Tiger Or Bull Shark Implicated,Y
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13.0,Unknown Bull And Tiger Sharks Frequent The Area,Y
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39.0,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11.0,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27.0,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12.0,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26.0,Suspected Gws,N
20,8th January,2026.0,Unprovoked,Us Virgin Islands,snorkeling,F,56.0,Unknown,Y
25,21st December,2025.0,Unprovoked,Usa,swimming,F,55.0,Great White Shark,Y
27,9th December,2025.0,Provoked,Usa,freeing trapped shark,M,24.0,Black Tip Reef Shark,N
28,27th November,2025.0,Unprovoked,Australia,swimming,M,26.0,3M Bull Shark,N
29,27th November,2025.0,Unprovoked,Australia,swimming,F,25.0,3M Bull Shark,Y
30,10th November,2025.0,Unprovoked,Australia,foil boarding,M,61.0,Great White Shark,N
31,9th November,2025.0,Unprovoked,French Polynesia,swimming,M,40.0,3M Shark,N
34,4th November,2025.0,Unprovoked,Samoa,surfing,M,13.0,Suspected Tiger Shark,N
35,14th October,2025.0,Unprovoked,Columbia,swimming with sharks,M,14.0,Nurse Shark,N
36,11th October,2025.0,Unprovoked,Australia,fishing/swimming,M,14.0,Tiger Or Bull Shark,N

Eliminar duplicados

In [34]:
df = df.drop_duplicates()

In [35]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026.0,Unprovoked,Australia,surfing,M,16.0,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,swimming,F,22.0,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,surfing,M,39.0,Great White Shark,N
9,22nd February,2026.0,Unprovoked,New Caledonia,wing foiling,M,55.0,Tiger Or Bull Shark Implicated,Y
11,29th January,2026.0,Unprovoked,Brazil,swimming,M,13.0,Unknown Bull And Tiger Sharks Frequent The Area,Y
14,20th January,2026.0,Unprovoked,Australia,surfing,M,39.0,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,surfing,M,11.0,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,surfing,M,27.0,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,jumping off rocks,M,12.0,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,surfing,M,26.0,Suspected Gws,N
20,8th January,2026.0,Unprovoked,Us Virgin Islands,snorkeling,F,56.0,Unknown,Y
25,21st December,2025.0,Unprovoked,Usa,swimming,F,55.0,Great White Shark,Y
27,9th December,2025.0,Provoked,Usa,freeing trapped shark,M,24.0,Black Tip Reef Shark,N
28,27th November,2025.0,Unprovoked,Australia,swimming,M,26.0,3M Bull Shark,N
29,27th November,2025.0,Unprovoked,Australia,swimming,F,25.0,3M Bull Shark,Y
30,10th November,2025.0,Unprovoked,Australia,foil boarding,M,61.0,Great White Shark,N
31,9th November,2025.0,Unprovoked,French Polynesia,swimming,M,40.0,3M Shark,N
34,4th November,2025.0,Unprovoked,Samoa,surfing,M,13.0,Suspected Tiger Shark,N
35,14th October,2025.0,Unprovoked,Columbia,swimming with sharks,M,14.0,Nurse Shark,N
36,11th October,2025.0,Unprovoked,Australia,fishing/swimming,M,14.0,Tiger Or Bull Shark,N

Vip: A ver me he cargado filas a tutiplen pero aun si queda un analisis FIABLE.

Si quedasen pocas pues suavizo lo de dropna.subset("x")

In [37]:
df.shape

(2227, 9)

---

  Ataques por actividad practicada

  Ataques por actividad practicada

  Ataques por sexo

  Ataques provocados vs no provocados

  Ataques por década

  Ataques por grupo de edad

  Ataques por pais

 ¿Qué actividades aparecen más?

¿Qué países tienen más ataques?

¿Cuántos ataques fueron fatales?

Ejemplos de preguntas que respondes aquí:

¿Qué actividades aparecen más?

¿Qué países tienen más ataques?

¿Cuántos ataques fueron fatales?

In [ ]:
Década del ataque

df["Decade"] = (df["Year"] // 10) * 10

6.2. Grupo de edad

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")


df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 30, 45, 60, 120],
    labels=["Niño", "Adolescente", "Joven", "Adulto", "Maduro", "Senior"])

6.3. Categoría simplificada de actividad

In [ ]:


def categorize_activity(x):
    if "surf" in x:
        return "Surf"
    if "swim" in x or "bathing" in x:
        return "Natación"
    if "fish" in x:
        return "Pesca"
    if "dive" in x:
        return "Buceo"
    if "kayak" in x or "canoe" in x:
        return "Kayak"
    return "Otras"


df["ActivityCategory"] = df["Activity"].apply(categorize_activity)

# Contar valores de cualquier columna

In [ ]:
df["Activity"].value_counts()
df["Country"].value_counts()
df["Type"].value_counts()
df["FatalY/N"].value_counts()

# Filtrar datos


Ataques fatales

In [ ]:
 
df[df["FatalY/N"] == "Y"]

Actividades que contienen “surf”

In [ ]:
df[df["Activity"].str.contains("surf", case=False, na=False)]

Mujeres atacadas

In [ ]:
df[df["Sex"] == "F"]

Ataques por país

In [ ]:
 
df[df["Country"] == "Australia"]




Ataques por año
 
df.groupby("Year").size()
Ataques por actividad
 
df.groupby("Activity").size().sort_values(ascending=False)
Ataques por país y actividad
 
df.groupby(["Country", "Activity"]).size()
Fatalidad por actividad
 
df.groupby("Activity")["FatalY/N"].value_counts()


Ejemplo: ataques entre 1990 y 2000
 
df[(df["Year"] >= 1990) & (df["Year"] <= 2000)]

Top 10 actividades
 
df["Activity"].value_counts().head(10).plot(kind="bar")
Fatalidad por actividad
 
df.groupby("Activity")["FatalY/N"].value_counts().unstack().plot(kind="bar")