# Proyecto de Análisis de Datos: Actividades Asociadas a Ataques de Tiburón

# 0 Enfoque

Objetivo del estudio 
El propósito de este proyecto es identificar qué actividades acuáticas aparecen con mayor frecuencia asociadas a ataques de tiburón   
segun los datos analizados de la web "(Global Shark Attack File)".

 Se basa en datos que no estan en tiempo real

A través de un proceso completo de:

exploración inicial

selección de variables relevantes

limpieza y normalización

análisis exploratorio (EDA)

visualización

análisis complementario de fatalidad

buscamos comprender en qué contextos y actividades se registran más incidentes.

# 1 Carga del dataset

In [34]:
import pandas as pd 
df = pd.read_excel("GSAF5.xls", engine="xlrd")
df.head() # Se visualizan las primeras filas para comprender la estructura general del dataset.

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2 Exploración inicial

Primero vemos alguna informacion del dataframe y como estan los ejes

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7087 entries, 0 to 7086
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7087 non-null   object
 1   Year            7085 non-null   float64
 2   Type            7069 non-null   str
 3   Country         7037 non-null   str
 4   State           6600 non-null   str
 5   Location        6520 non-null   str
 6   Activity        6504 non-null   str
 7   Name            6869 non-null   str
 8   Sex             6509 non-null   str
 9   Age             4093 non-null   object
 10  Injury          7051 non-null   str
 11  Fatal Y/N       6526 non-null   object
 12  Time            3560 non-null   object
 13  Species         3956 non-null   str
 14  Source          7067 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   str
 17  href            6796 non-null   str
 18  Case Number     6798 non-null   str
 19  Case Number.1   6797 non-null   str
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      str
 22  Unnamed: 22     2 non-null      str
dtypes: float64(2), object(6), str(15)
memory usage: 1.2+ MB

  
El dataset tiene 23 columnas, aunque visualmente parezcan menos.

Los nombres están desordenados, con espacios y formatos inconsistentes.

In [36]:
lista_columnas = df.columns.tolist()
lista_columnas

['Date',
 'Year',
 'Type',
 'Country',
 'State',
 'Location',
 'Activity',
 'Name',
 'Sex',
 'Age',
 'Injury',
 'Fatal Y/N',
 'Time',
 'Species ',
 'Source',
 'pdf',
 'href formula',
 'href',
 'Case Number',
 'Case Number.1',
 'original order',
 'Unnamed: 21',
 'Unnamed: 22']

VIP: Para ver los tipos de cada columna

In [37]:
def ver_tipos_columnas(df,lista_columnas):
    for x in lista_columnas:
        print(df[x].apply(type).value_counts())
        print("---------------------------")

print(ver_tipos_columnas(df,lista_columnas))

Date
<class 'str'>                  6866
<class 'int'>                   150
<class 'datetime.datetime'>      71
Name: count, dtype: int64
---------------------------
Year
<class 'float'>    7087
Name: count, dtype: int64
---------------------------
Type
<class 'str'>      7069
<class 'float'>      18
Name: count, dtype: int64
---------------------------
Country
<class 'str'>      7037
<class 'float'>      50
Name: count, dtype: int64
---------------------------
State
<class 'str'>      6600
<class 'float'>     487
Name: count, dtype: int64
---------------------------
Location
<class 'str'>      6520
<class 'float'>     567
Name: count, dtype: int64
---------------------------
Activity
<class 'str'>      6504
<class 'float'>     583
Name: count, dtype: int64
---------------------------
Name
<class 'str'>      6869
<class 'float'>     218
Name: count, dtype: int64
---------------------------
Sex
<class 'str'>      6509
<class 'float'>     578
Name: count, dtype: int64
---------------------------
Age
<class 'float'>    2994
<class 'int'>      2053
<class 'str'>      2040
Name: count, dtype: int64
---------------------------
Injury
<class 'str'>      7051
<class 'float'>      36
Name: count, dtype: int64
---------------------------
Fatal Y/N
<class 'str'>      6525
<class 'float'>     561
<class 'int'>         1
Name: count, dtype: int64
---------------------------
Time
<class 'str'>      3553
<class 'float'>    3528
<class 'int'>         6
Name: count, dtype: int64
---------------------------
Species
<class 'str'>      3956
<class 'float'>    3131
Name: count, dtype: int64
---------------------------
Source
<class 'str'>                  7065
<class 'float'>                  20
<class 'datetime.datetime'>       2
Name: count, dtype: int64
---------------------------
pdf
<class 'str'>      6798
<class 'float'>     289
Name: count, dtype: int64
---------------------------
href formula
<class 'str'>      6794
<class 'float'>     293
Name: count, dtype: int64
---------------------------
href
<class 'str'>      6796
<class 'float'>     291
Name: count, dtype: int64
---------------------------
Case Number
<class 'str'>      6798
<class 'float'>     289
Name: count, dtype: int64
---------------------------
Case Number.1
<class 'str'>      6797
<class 'float'>     290
Name: count, dtype: int64
---------------------------
original order
<class 'float'>    7087
Name: count, dtype: int64
---------------------------
Unnamed: 21
<class 'float'>    7086
<class 'str'>         1
Name: count, dtype: int64
---------------------------
Unnamed: 22
<class 'float'>    7085
<class 'str'>         2
Name: count, dtype: int64
---------------------------
None

In [38]:
def eliminar_minoritarios(df, lista_columnas):
    for col in lista_columnas:
        print(f"\nProcesando columna: {col}")

        # Detectar tipo mayoritario
        tipo_mayoritario = df[col].apply(type).value_counts().idxmax()
        print(f"Tipo mayoritario en {col}: {tipo_mayoritario}")

        # Filtrar solo filas del tipo mayoritario
        df = df[df[col].apply(lambda v: isinstance(v, tipo_mayoritario))]

    return df

eliminar_minoritarios(df,lista_columnas)
print(ver_tipos_columnas(df,lista_columnas))

Procesando columna: Date
Tipo mayoritario en Date: <class 'str'>

Procesando columna: Year
Tipo mayoritario en Year: <class 'float'>

Procesando columna: Type
Tipo mayoritario en Type: <class 'str'>

Procesando columna: Country
Tipo mayoritario en Country: <class 'str'>

Procesando columna: State
Tipo mayoritario en State: <class 'str'>

Procesando columna: Location
Tipo mayoritario en Location: <class 'str'>

Procesando columna: Activity
Tipo mayoritario en Activity: <class 'str'>

Procesando columna: Name
Tipo mayoritario en Name: <class 'str'>

Procesando columna: Sex
Tipo mayoritario en Sex: <class 'str'>

Procesando columna: Age
Tipo mayoritario en Age: <class 'int'>

Procesando columna: Injury
Tipo mayoritario en Injury: <class 'str'>

Procesando columna: Fatal Y/N
Tipo mayoritario en Fatal Y/N: <class 'str'>

Procesando columna: Time
Tipo mayoritario en Time: <class 'str'>

Procesando columna: Species
Tipo mayoritario en Species : <class 'str'>

Procesando columna: Source
Tipo mayoritario en Source: <class 'str'>

Procesando columna: pdf
Tipo mayoritario en pdf: <class 'str'>

Procesando columna: href formula
Tipo mayoritario en href formula: <class 'str'>

Procesando columna: href
Tipo mayoritario en href: <class 'str'>

Procesando columna: Case Number
Tipo mayoritario en Case Number: <class 'str'>

Procesando columna: Case Number.1
Tipo mayoritario en Case Number.1: <class 'str'>

Procesando columna: original order
Tipo mayoritario en original order: <class 'float'>

Procesando columna: Unnamed: 21
Tipo mayoritario en Unnamed: 21: <class 'float'>

Procesando columna: Unnamed: 22
Tipo mayoritario en Unnamed: 22: <class 'float'>
Date
<class 'str'>                  6866
<class 'int'>                   150
<class 'datetime.datetime'>      71
Name: count, dtype: int64
---------------------------
Year
<class 'float'>    7087
Name: count, dtype: int64
---------------------------
Type
<class 'str'>      7069
<class 'float'>      18
Name: count, dtype: int64
---------------------------
Country
<class 'str'>      7037
<class 'float'>      50
Name: count, dtype: int64
---------------------------
State
<class 'str'>      6600
<class 'float'>     487
Name: count, dtype: int64
---------------------------
Location
<class 'str'>      6520
<class 'float'>     567
Name: count, dtype: int64
---------------------------
Activity
<class 'str'>      6504
<class 'float'>     583
Name: count, dtype: int64
---------------------------
Name
<class 'str'>      6869
<class 'float'>     218
Name: count, dtype: int64
---------------------------
Sex
<class 'str'>      6509
<class 'float'>     578
Name: count, dtype: int64
---------------------------
Age
<class 'float'>    2994
<class 'int'>      2053
<class 'str'>      2040
Name: count, dtype: int64
---------------------------
Injury
<class 'str'>      7051
<class 'float'>      36
Name: count, dtype: int64
---------------------------
Fatal Y/N
<class 'str'>      6525
<class 'float'>     561
<class 'int'>         1
Name: count, dtype: int64
---------------------------
Time
<class 'str'>      3553
<class 'float'>    3528
<class 'int'>         6
Name: count, dtype: int64
---------------------------
Species
<class 'str'>      3956
<class 'float'>    3131
Name: count, dtype: int64
---------------------------
Source
<class 'str'>                  7065
<class 'float'>                  20
<class 'datetime.datetime'>       2
Name: count, dtype: int64
---------------------------
pdf
<class 'str'>      6798
<class 'float'>     289
Name: count, dtype: int64
---------------------------
href formula
<class 'str'>      6794
<class 'float'>     293
Name: count, dtype: int64
---------------------------
href
<class 'str'>      6796
<class 'float'>     291
Name: count, dtype: int64
---------------------------
Case Number
<class 'str'>      6798
<class 'float'>     289
Name: count, dtype: int64
---------------------------
Case Number.1
<class 'str'>      6797
<class 'float'>     290
Name: count, dtype: int64
---------------------------
original order
<class 'float'>    7087
Name: count, dtype: int64
---------------------------
Unnamed: 21
<class 'float'>    7086
<class 'str'>         1
Name: count, dtype: int64
---------------------------
Unnamed: 22
<class 'float'>    7085
<class 'str'>         2
Name: count, dtype: int64
---------------------------
None

# 1) Limpia nombres de columnas (solo una vez)

Para escoger las columnas que hacemos el estudio primero vamos a limpiar ese indice y dejarlas en Capital Case

In [39]:

df.columns = (
    df.columns.astype(str)
    .str.strip()
    .str.title()
    .str.replace(" ", "")
)

In [40]:
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,Pdf,HrefFormula,Href,CaseNumber,CaseNumber.1,OriginalOrder,Unnamed:21,Unnamed:22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.columns # Comprobamos visualmente

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'FatalY/N', 'Time', 'Species', 'Source',
       'Pdf', 'HrefFormula', 'Href', 'CaseNumber', 'CaseNumber.1',
       'OriginalOrder', 'Unnamed:21', 'Unnamed:22'],
      dtype='str')

# 4 Selección de columnas relevantes

 Columna   : Descripción         
 Date      : Para ver la estacion     
 Year      : Año del ataque      
 Type      : Provocado / No provocado   
 Country   : País del incidente      
 Activity  : Actividad registrada     
 Sex       : Sexo de la víctima      
 Age       : Edad (convertida a numérico) 
 Species   : Specie de tiburion      
 Fatal Y/N : Si fue fatal

Ahora escogemos la lsita que queramos usar sin miedo MANUAL

In [42]:
lista_escogida = [
    "Date",
    "Year",
    "Type",
    "Country",
    "Activity",
    "Sex",
    "Age",
    "Species",
    "FatalY/N"   # OJITO CON ESTE me dio muchos problemas
]
numero_lista_escogida = len (lista_escogida)
print(f"numero_elementos_df_final: {numero_lista_escogida}")

numero_elementos_df_final: 9

Para asegurarno que estan todas en la lista primero haremos un

In [43]:
def comprueba_estan(lista, df):
    for x in lista:
        if x in df.columns:
            print(f"{x} → OK")
        else:
            print(f"{x} → NO está en el DataFrame")

Comprueba si la lista esta:

In [44]:
comprueba_estan(lista_escogida,df)
print

Date → OK
Year → OK
Type → OK
Country → OK
Activity → OK
Sex → OK
Age → OK
Species → OK
FatalY/N → OK

# 6 Selección final del DataFrame

Ahora aplico el filtro al DataFrame

In [45]:
df = df[lista_escogida]
df.head()

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,UNprovoked,Maldives,Swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,Diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,Surfing,M,30+,Unknown,N

# Limpieza Datos de esas columnas

Primero vuelvo a ver los datos

In [46]:
df.head()

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,UNprovoked,Maldives,Swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,Diving,M,?,Great White Shark 3.5m (11.5ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,Surfing,M,30+,Unknown,N

Creo mis listas de limpieza

In [48]:
lista_strings_a_Capital = ["Type","Country","Activity","Sex","Species","FatalY/N"]
lista_string_numeros = ["Age"]
lista_float_int = ['Year']

Creo mis funciones de limpieza

In [49]:
def strings_a_Capital(df, lista_columnas):
    for col in lista_columnas:
        df[col] = (
            df[col]
            .where(df[col].notna())   # mantiene NaN
            .astype(str)
            .str.strip()
            .str.title()
        )
    return df

In [50]:
def convertir_edad(df, columnas):
    for col in columnas:
        # 1) Convertir a string para limpiar
        df[col] = df[col].astype("string").str.strip()

        # 2) Reemplazar valores basura
        basura = ["nan", "none", "unknown", "na", "", " ", "null", "n/a"]
        df[col] = df[col].replace(basura, pd.NA)

        # 3) Convertir a número
        df[col] = pd.to_numeric(df[col], errors="coerce")

        # 4) Convertir floats tipo 25.0 a enteros
        df[col] = df[col].astype("Int64")

        # 5) Eliminar edades imposibles
        df.loc[(df[col] < 1) | (df[col] > 120), col] = pd.NA

    return df

Aplica funciones en este orden

Limpia strings SOLO en columnas de texto

In [51]:
df = strings_a_Capital(df, lista_strings_a_Capital)

In [52]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,Swimming,M,?,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,Diving,M,?,Great White Shark 3.5M (11.5Ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,Surfing,M,30+,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,Swimming,F,?,Unknown Shark 5Ft (1.5M),N
7,10th March,2026.0,Unprovoked,Australia,Wing Foiling,M,?,Great White Shark 10Ft (3M),N
8,5th March,2026.0,Unprovoked,Australia,Snorkeling,M,50's,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,Diving,M,?,Juvenile Tiger Shark 7Ft (2.1M),N
11,29th January,2026.0,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
12,29th January,2026.0,Unprovoked,Australia,Surfing,M,?,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,Swimming,F,?,1.7M Seven Gill Shark,N
14,20th January,2026.0,Unprovoked,Australia,Surfing,M,39,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,Surfing,M,11,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,Surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,Jumping Off Rocks,M,12,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,Surfing,M,26,Suspected Gws,N
19,10th January,2026.0,Unprovoked,Australia,Surfing,M,?,Unknown,N

Convierte edad SOLO después de limpiar strings

In [53]:
df = convertir_edad(df, ["Age"])

In [54]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026.0,Unprovoked,Maldives,Swimming,M,<NA>,Unknown,N
1,3rd April,2026.0,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026.0,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026.0,Unprovoked,Australia,Diving,M,<NA>,Great White Shark 3.5M (11.5Ft),N
4,22nd-23rd March,2026.0,Unprovoked,Australia,Surfing,M,<NA>,Unknown,N
5,18th March,2026.0,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
6,14th March,2026.0,Unprovoked,Australia,Swimming,F,<NA>,Unknown Shark 5Ft (1.5M),N
7,10th March,2026.0,Unprovoked,Australia,Wing Foiling,M,<NA>,Great White Shark 10Ft (3M),N
8,5th March,2026.0,Unprovoked,Australia,Snorkeling,M,<NA>,Unknown,N
9,22nd February,2026.0,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
10,6th February,2026.0,Unprovoked,Cayman Islands,Diving,M,<NA>,Juvenile Tiger Shark 7Ft (2.1M),N
11,29th January,2026.0,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
12,29th January,2026.0,Unprovoked,Australia,Surfing,M,<NA>,Unknown,N
13,24th January,2026.0,Unprovoked,Australia,Swimming,F,<NA>,1.7M Seven Gill Shark,N
14,20th January,2026.0,Unprovoked,Australia,Surfing,M,39,Bull Shark,N
15,19th January,2026.0,Unprovoked,Australia,Surfing,M,11,Bull Shark,N
16,19th January,2026.0,Unprovoked,Australia,Surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026.0,Unprovoked,Australia,Jumping Off Rocks,M,12,Bull Shark,Y
18,13th January,2026.0,Unprovoked,Usa,Surfing,M,26,Suspected Gws,N
19,10th January,2026.0,Unprovoked,Australia,Surfing,M,<NA>,Unknown,N

Convierte Year a número

In [55]:
df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")

In [56]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
0,14/04,2026,Unprovoked,Maldives,Swimming,M,<NA>,Unknown,N
1,3rd April,2026,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
3,25th March,2026,Unprovoked,Australia,Diving,M,<NA>,Great White Shark 3.5M (11.5Ft),N
4,22nd-23rd March,2026,Unprovoked,Australia,Surfing,M,<NA>,Unknown,N
5,18th March,2026,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
6,14th March,2026,Unprovoked,Australia,Swimming,F,<NA>,Unknown Shark 5Ft (1.5M),N
7,10th March,2026,Unprovoked,Australia,Wing Foiling,M,<NA>,Great White Shark 10Ft (3M),N
8,5th March,2026,Unprovoked,Australia,Snorkeling,M,<NA>,Unknown,N
9,22nd February,2026,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
10,6th February,2026,Unprovoked,Cayman Islands,Diving,M,<NA>,Juvenile Tiger Shark 7Ft (2.1M),N
11,29th January,2026,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
12,29th January,2026,Unprovoked,Australia,Surfing,M,<NA>,Unknown,N
13,24th January,2026,Unprovoked,Australia,Swimming,F,<NA>,1.7M Seven Gill Shark,N
14,20th January,2026,Unprovoked,Australia,Surfing,M,39,Bull Shark,N
15,19th January,2026,Unprovoked,Australia,Surfing,M,11,Bull Shark,N
16,19th January,2026,Unprovoked,Australia,Surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026,Unprovoked,Australia,Jumping Off Rocks,M,12,Bull Shark,Y
18,13th January,2026,Unprovoked,Usa,Surfing,M,26,Suspected Gws,N
19,10th January,2026,Unprovoked,Australia,Surfing,M,<NA>,Unknown,N

In [57]:
df = df.dropna()

In [58]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
5,18th March,2026,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
9,22nd February,2026,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
11,29th January,2026,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
14,20th January,2026,Unprovoked,Australia,Surfing,M,39,Bull Shark,N
15,19th January,2026,Unprovoked,Australia,Surfing,M,11,Bull Shark,N
16,19th January,2026,Unprovoked,Australia,Surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026,Unprovoked,Australia,Jumping Off Rocks,M,12,Bull Shark,Y
18,13th January,2026,Unprovoked,Usa,Surfing,M,26,Suspected Gws,N
20,8th January,2026,Unprovoked,Us Virgin Islands,Snorkeling,F,56,Unknown,Y
25,21st December,2025,Unprovoked,Usa,Swimming,F,55,Great White Shark,Y
27,9th December,2025,Provoked,Usa,Freeing Trapped Shark,M,24,Black Tip Reef Shark,N
28,27th November,2025,Unprovoked,Australia,Swimming,M,26,3M Bull Shark,N
29,27th November,2025,Unprovoked,Australia,Swimming,F,25,3M Bull Shark,Y
30,10th November,2025,Unprovoked,Australia,Foil Boarding,M,61,Great White Shark,N
31,9th November,2025,Unprovoked,French Polynesia,Swimming,M,40,3M Shark,N
34,4th November,2025,Unprovoked,Samoa,Surfing,M,13,Suspected Tiger Shark,N
35,14th October,2025,Unprovoked,Columbia,Swimming With Sharks,M,14,Nurse Shark,N
36,11th October,2025,Unprovoked,Australia,Fishing/Swimming,M,14,Tiger Or Bull Shark,N

In [59]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
5,18th March,2026,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
9,22nd February,2026,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
11,29th January,2026,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
14,20th January,2026,Unprovoked,Australia,Surfing,M,39,Bull Shark,N
15,19th January,2026,Unprovoked,Australia,Surfing,M,11,Bull Shark,N
16,19th January,2026,Unprovoked,Australia,Surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026,Unprovoked,Australia,Jumping Off Rocks,M,12,Bull Shark,Y
18,13th January,2026,Unprovoked,Usa,Surfing,M,26,Suspected Gws,N
20,8th January,2026,Unprovoked,Us Virgin Islands,Snorkeling,F,56,Unknown,Y
25,21st December,2025,Unprovoked,Usa,Swimming,F,55,Great White Shark,Y
27,9th December,2025,Provoked,Usa,Freeing Trapped Shark,M,24,Black Tip Reef Shark,N
28,27th November,2025,Unprovoked,Australia,Swimming,M,26,3M Bull Shark,N
29,27th November,2025,Unprovoked,Australia,Swimming,F,25,3M Bull Shark,Y
30,10th November,2025,Unprovoked,Australia,Foil Boarding,M,61,Great White Shark,N
31,9th November,2025,Unprovoked,French Polynesia,Swimming,M,40,3M Shark,N
34,4th November,2025,Unprovoked,Samoa,Surfing,M,13,Suspected Tiger Shark,N
35,14th October,2025,Unprovoked,Columbia,Swimming With Sharks,M,14,Nurse Shark,N
36,11th October,2025,Unprovoked,Australia,Fishing/Swimming,M,14,Tiger Or Bull Shark,N

In [60]:
df = df.drop_duplicates()

In [61]:
df.head(20)

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
5,18th March,2026,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
9,22nd February,2026,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
11,29th January,2026,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y
14,20th January,2026,Unprovoked,Australia,Surfing,M,39,Bull Shark,N
15,19th January,2026,Unprovoked,Australia,Surfing,M,11,Bull Shark,N
16,19th January,2026,Unprovoked,Australia,Surfing,M,27,5M Shark Species Not Determined,N
17,18th January,2026,Unprovoked,Australia,Jumping Off Rocks,M,12,Bull Shark,Y
18,13th January,2026,Unprovoked,Usa,Surfing,M,26,Suspected Gws,N
20,8th January,2026,Unprovoked,Us Virgin Islands,Snorkeling,F,56,Unknown,Y
25,21st December,2025,Unprovoked,Usa,Swimming,F,55,Great White Shark,Y
27,9th December,2025,Provoked,Usa,Freeing Trapped Shark,M,24,Black Tip Reef Shark,N
28,27th November,2025,Unprovoked,Australia,Swimming,M,26,3M Bull Shark,N
29,27th November,2025,Unprovoked,Australia,Swimming,F,25,3M Bull Shark,Y
30,10th November,2025,Unprovoked,Australia,Foil Boarding,M,61,Great White Shark,N
31,9th November,2025,Unprovoked,French Polynesia,Swimming,M,40,3M Shark,N
34,4th November,2025,Unprovoked,Samoa,Surfing,M,13,Suspected Tiger Shark,N
35,14th October,2025,Unprovoked,Columbia,Swimming With Sharks,M,14,Nurse Shark,N
36,11th October,2025,Unprovoked,Australia,Fishing/Swimming,M,14,Tiger Or Bull Shark,N

In [ ]:
ver_tipos_columnas(df, lista_escogida)  # Date es IMPOSIBLE no intento mas

Date
<class 'str'>                  2161
<class 'datetime.datetime'>      62
<class 'int'>                     4
Name: count, dtype: int64
---------------------------
Year
<class 'int'>    2227
Name: count, dtype: int64
---------------------------
Type
<class 'str'>    2227
Name: count, dtype: int64
---------------------------
Country
<class 'str'>    2227
Name: count, dtype: int64
---------------------------
Activity
<class 'str'>    2227
Name: count, dtype: int64
---------------------------
Sex
<class 'str'>    2227
Name: count, dtype: int64
---------------------------
Age
<class 'int'>    2227
Name: count, dtype: int64
---------------------------
Species
<class 'str'>    2227
Name: count, dtype: int64
---------------------------
FatalY/N
<class 'str'>    2227
Name: count, dtype: int64
---------------------------

In [63]:
df.shape

(2227, 9)

In [64]:
df.head()

,Date,Year,Type,Country,Activity,Sex,Age,Species,FatalY/N
1,3rd April,2026,Unprovoked,Australia,Surfing,M,16,Bronze Whaler,N
2,26th March,2026,Unprovoked,Bahamas,Swimming,F,22,Unknown,N
5,18th March,2026,Unprovoked,Usa,Surfing,M,39,Great White Shark,N
9,22nd February,2026,Unprovoked,New Caledonia,Wing Foiling,M,55,Tiger Or Bull Shark Implicated,Y
11,29th January,2026,Unprovoked,Brazil,Swimming,M,13,Unknown Bull And Tiger Sharks Frequent The Area,Y

In [ ]:
print(ver_tipos_columnas(df,lista_columnas))

Paso 1: detectar el tipo mayoritario

---

  Ataques por actividad practicada

  Ataques por actividad practicada

  Ataques por sexo

  Ataques provocados vs no provocados

  Ataques por década

  Ataques por grupo de edad

  Ataques por pais

 ¿Qué actividades aparecen más?

¿Qué países tienen más ataques?

¿Cuántos ataques fueron fatales?

Ejemplos de preguntas que respondes aquí:

¿Qué actividades aparecen más?

¿Qué países tienen más ataques?

¿Cuántos ataques fueron fatales?

In [ ]:
Década del ataque

df["Decade"] = (df["Year"] // 10) * 10

6.2. Grupo de edad

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")


df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 30, 45, 60, 120],
    labels=["Niño", "Adolescente", "Joven", "Adulto", "Maduro", "Senior"])

6.3. Categoría simplificada de actividad

In [ ]:


def categorize_activity(x):
    if "surf" in x:
        return "Surf"
    if "swim" in x or "bathing" in x:
        return "Natación"
    if "fish" in x:
        return "Pesca"
    if "dive" in x:
        return "Buceo"
    if "kayak" in x or "canoe" in x:
        return "Kayak"
    return "Otras"


df["ActivityCategory"] = df["Activity"].apply(categorize_activity)

# Contar valores de cualquier columna

In [ ]:
df["Activity"].value_counts()
df["Country"].value_counts()
df["Type"].value_counts()
df["FatalY/N"].value_counts()

# Filtrar datos


Ataques fatales

In [ ]:
 
df[df["FatalY/N"] == "Y"]

Actividades que contienen “surf”

In [ ]:
df[df["Activity"].str.contains("surf", case=False, na=False)]

Mujeres atacadas

In [ ]:
df[df["Sex"] == "F"]

Ataques por país

In [ ]:
 
df[df["Country"] == "Australia"]




Ataques por año
 
df.groupby("Year").size()
Ataques por actividad
 
df.groupby("Activity").size().sort_values(ascending=False)
Ataques por país y actividad
 
df.groupby(["Country", "Activity"]).size()
Fatalidad por actividad
 
df.groupby("Activity")["FatalY/N"].value_counts()


Ejemplo: ataques entre 1990 y 2000
 
df[(df["Year"] >= 1990) & (df["Year"] <= 2000)]

Top 10 actividades
 
df["Activity"].value_counts().head(10).plot(kind="bar")
Fatalidad por actividad
 
df.groupby("Activity")["FatalY/N"].value_counts().unstack().plot(kind="bar")