Business Problem

Queremos analizar qué actividades están más asociadas a ataques de tiburón para identificar qué prácticas acuáticas presentan mayor riesgo.

In [2]:
import pandas as pd
import numpy as np

!pip install xlrd #

In [ ]:
import pandas as pd
df = pd.read_excel("GSAF5.xls", engine="xlrd")
print(df.head())

In [4]:
df.head() #ver el dataframe

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape #ver tamaño del dataset

(7087, 23)

In [6]:
df.columns #ver el nombre de las columnas

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

In [7]:
df.info() #ver info general

<class 'pandas.DataFrame'>
RangeIndex: 7087 entries, 0 to 7086
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7087 non-null   object
 1   Year            7085 non-null   float64
 2   Type            7069 non-null   str
 3   Country         7037 non-null   str
 4   State           6600 non-null   str
 5   Location        6520 non-null   str
 6   Activity        6504 non-null   str
 7   Name            6869 non-null   str
 8   Sex             6509 non-null   str
 9   Age             4093 non-null   object
 10  Injury          7051 non-null   str
 11  Fatal Y/N       6526 non-null   object
 12  Time            3560 non-null   object
 13  Species         3956 non-null   str
 14  Source          7067 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   str
 17  href            6796 non-null   str
 18  Case Number     6798 non-null   str
 19  Case Number.1   6797 non-null   str
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      str
 22  Unnamed: 22     2 non-null      str
dtypes: float64(2), object(6), str(15)
memory usage: 1.2+ MB

In [8]:
df.isna().sum() #detectar nulos

Date                 0
Year                 2
Type                18
Country             50
State              487
Location           567
Activity           583
Name               218
Sex                578
Age               2994
Injury              36
Fatal Y/N          561
Time              3527
Species           3131
Source              20
pdf                288
href formula       293
href               291
Case Number        289
Case Number.1      290
original order     288
Unnamed: 21       7086
Unnamed: 22       7085
dtype: int64

In [9]:
df.duplicated().sum() #detecta duplicados

np.int64(0)

In [10]:
df = df.drop_duplicates() # elimina duplicados

In [11]:
df = df[["Activity","Country","Year","Sex","Age","Fatal Y/N"]] # decido usar estas columnas

In [12]:
df.head() # miro a ver como me quedo, vuelvo a ver el dataset

   Activity    Country    Year Sex  Age Fatal Y/N
0  Swimming   Maldives  2026.0   M    ?         N
1   Surfing  Australia  2026.0   M   16         N
2  Swimming    Bahamas  2026.0   F   22         N
3    Diving  Australia  2026.0   M    ?         N
4   Surfing  Australia  2026.0   M  30+         N

In [13]:
df.isna().sum() # ver por ejemplo activity, si es nulo no me sirve

Activity      583
Country        50
Year            2
Sex           578
Age          2994
Fatal Y/N     561
dtype: int64

In [ ]:
df = df.dropna(subset=["Fatal Y/N"]) # elimino filas que no tengan datos o valores o que no me sirvan

Hypotesis
Algunas actividades acuáticas como surfing o swimming aparecen más frecuentemente asociadas a ataques de tiburón en el dataset.

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 6504 entries, 0 to 7086
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Activity   6504 non-null   str
 1   Country    6461 non-null   str
 2   Year       6502 non-null   float64
 3   Sex        6079 non-null   str
 4   Age        3932 non-null   object
 5   Fatal Y/N  6070 non-null   object
dtypes: float64(1), object(2), str(3)
memory usage: 355.7+ KB

In [16]:
df.to_pickle("datos.pkl") # para volver a usar df = pd.read_pickle("datos.pkl")

In [21]:
df['Fatal Y/N'].value_counts()

Fatal Y/N
N          4635
Y          1382
UNKNOWN      36
F             5
 N            5
M             2
n             1
Nq            1
2017          1
Y x 2         1
y             1
Name: count, dtype: int64

22 de abril

In [ ]:
df["Fatal Y/N"] = df["Fatal Y/N"].str.strip().str.upper() # normalice texto

In [ ]:
# aca lo que hice fue reemplazar esos valores raros con nulos
df["Fatal Y/N"] = df["Fatal Y/N"].replace(
    ["UNKNOWN", "F", "M", "NQ", "2017", "Y X 2"],
    np.nan
)

In [26]:
df["Fatal Y/N"].value_counts(dropna=False) # revisado de nuevo quedaría asi.

Fatal Y/N
N      4641
Y      1383
NaN     480
Name: count, dtype: int64

REVISAR DUPLICADOS DE NUEVO:

In [27]:
df.duplicated().sum()

np.int64(291)

In [28]:
df = df.drop_duplicates()

In [29]:
df.duplicated().sum()

np.int64(0)

REVISO NULOS DE NUEVO:

In [30]:
df.isna().sum()

Activity        0
Country        42
Year            2
Sex           407
Age          2373
Fatal Y/N     475
dtype: int64

In [31]:
# Actividades con mas ataques:
df.groupby("Activity").size().sort_values(ascending=False).head(10)

Activity
Surfing         997
Swimming        983
Fishing         452
Spearfishing    369
Wading          177
Bathing         158
Diving          145
Snorkeling      135
Standing        111
Scuba diving     83
dtype: int64

Con esto veo que el Surfing y el Swimming encabezan el riesgo de ataques.

In [32]:
# ¿Qué actividades tienen más ataques fatales? : groupby en Actividad y fatalidad
df.groupby(["Activity","Fatal Y/N"]).size()

Activity                                                                    Fatal Y/N
                                                                            N            1
                                                                            N            1
 Diving for abalone (Hookah)                                                N            1
 a canoe was pursuing a schooner that had forcibily abducted 5 young girls  Y            1
"Boat accident"                                                             Y            1
                                                                                        ..
snorkeling                                                                  N            1
snorkelling                                                                 N            1
wreck of the State Oil Company ship Permina                                 Y            1
yachting accident                                                           Y            1
yachtsman in a zodiac                                                       N            1
Length: 1579, dtype: int64

In [33]:
# En qué países ocurren más ataques dependiendo de la actividad? (USA y Australia)
df.groupby(["Country","Activity"]).size().sort_values(ascending=False).head(15)

Country       Activity
USA           Surfing         555
              Swimming        350
AUSTRALIA     Surfing         206
              Swimming        182
USA           Fishing         126
              Wading          123
AUSTRALIA     Fishing         109
SOUTH AFRICA  Surfing          95
              Swimming         86
AUSTRALIA     Spearfishing     78
USA           Standing         69
              Spearfishing     61
AUSTRALIA     Bathing          56
SOUTH AFRICA  Spearfishing     49
USA           Snorkeling       41
dtype: int64

In [34]:
# Ahora para resumir valores y buscar top values:
df.groupby("Activity").size().nlargest(10)

Activity
Surfing         997
Swimming        983
Fishing         452
Spearfishing    369
Wading          177
Bathing         158
Diving          145
Snorkeling      135
Standing        111
Scuba diving     83
dtype: int64

In [35]:
# Actividades con mas ataques
df.groupby("Activity").size().sort_values(ascending=False).head(10)

Activity
Surfing         997
Swimming        983
Fishing         452
Spearfishing    369
Wading          177
Bathing         158
Diving          145
Snorkeling      135
Standing        111
Scuba diving     83
dtype: int64

In [36]:
# Actividades vs fatalidad
df.groupby(["Activity","Fatal Y/N"]).size()

Activity                                                                    Fatal Y/N
                                                                            N            1
                                                                            N            1
 Diving for abalone (Hookah)                                                N            1
 a canoe was pursuing a schooner that had forcibily abducted 5 young girls  Y            1
"Boat accident"                                                             Y            1
                                                                                        ..
snorkeling                                                                  N            1
snorkelling                                                                 N            1
wreck of the State Oil Company ship Permina                                 Y            1
yachting accident                                                           Y            1
yachtsman in a zodiac                                                       N            1
Length: 1579, dtype: int64

In [37]:
# Actividades por país
df.groupby(["Country","Activity"]).size().sort_values(ascending=False).head(15)

Country       Activity
USA           Surfing         555
              Swimming        350
AUSTRALIA     Surfing         206
              Swimming        182
USA           Fishing         126
              Wading          123
AUSTRALIA     Fishing         109
SOUTH AFRICA  Surfing          95
              Swimming         86
AUSTRALIA     Spearfishing     78
USA           Standing         69
              Spearfishing     61
AUSTRALIA     Bathing          56
SOUTH AFRICA  Spearfishing     49
USA           Snorkeling       41
dtype: int64

POR EPOCA DEL AÑO: